import React from 'react';
import { X, Layers, FileCode, Download, FolderArchive } from 'lucide-react';

export default function ArtifactsModal({ isOpen, onClose, workspaceFiles = {} }) {
  if (!isOpen) return null;

  let filesObj = workspaceFiles;
  if (!filesObj || Object.keys(filesObj).length === 0) {
    try {
      const saved = localStorage.getItem('malvos_active_workspace_files');
      if (saved) filesObj = JSON.parse(saved);
    } catch {}
  }

  const fileEntries = Object.entries(filesObj || {}).map(([filePath, content]) => {
    const name = filePath.split('/').pop() || filePath;
    const ext = name.split('.').pop()?.toUpperCase() || 'FILE';
    const bytes = typeof content === 'string' ? new Blob([content]).size : 0;
    const size = bytes > 1024 ? `${(bytes / 1024).toFixed(1)} KB` : `${bytes} B`;
    return {
      path: filePath,
      name,
      type: ext,
      size,
      content: typeof content === 'string' ? content : ''
    };
  });

  const handleDownload = (entry) => {
    const blob = new Blob([entry.content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = entry.name;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/80 backdrop-blur-md animate-in fade-in duration-200">
      <div className="relative w-full max-w-xl bg-[#1a1a1a] border border-[#2b2b2b] rounded-3xl p-6 shadow-2xl overflow-hidden font-sans">
        {/* Close Button */}
        <button
          onClick={onClose}
          className="absolute top-5 right-5 p-2 text-neutral-400 hover:text-white rounded-full bg-[#242424] hover:bg-[#2d2d2d] transition-colors cursor-pointer"
        >
          <X size={17} />
        </button>

        <div className="mb-5">
          <h2 className="text-xl font-medium text-white flex items-center gap-2">
            <Layers className="text-emerald-400" size={19} />
            <span>Workspace Artifacts & Files</span>
          </h2>
          <p className="text-xs text-neutral-400 mt-1">
            Real code files, schemas, and documents generated in your active workspace session.
          </p>
        </div>

        {fileEntries.length === 0 ? (
          <div className="py-12 flex flex-col items-center justify-center text-center">
            <div className="w-12 h-12 rounded-2xl bg-[#222222] border border-[#303030] flex items-center justify-center text-neutral-500 mb-3">
              <FolderArchive size={22} />
            </div>
            <p className="text-xs text-neutral-400 font-medium">No files in current workspace</p>
            <p className="text-[11px] text-neutral-500 mt-0.5">Files generated by Calvras will automatically appear here.</p>
          </div>
        ) : (
          <div className="space-y-2 max-h-72 overflow-y-auto pr-1">
            {fileEntries.map((art) => (
              <div
                key={art.path}
                className="flex items-center justify-between p-3 rounded-xl bg-[#222222] border border-[#2d2d2d] hover:border-[#3d3d3d] transition-colors"
              >
                <div className="flex items-center gap-3 truncate">
                  <div className="w-8 h-8 rounded-lg bg-[#2b2b2b] flex items-center justify-center text-neutral-300 flex-shrink-0">
                    <FileCode size={16} />
                  </div>
                  <div className="truncate">
                    <div className="text-xs font-semibold text-neutral-200 truncate font-mono">{art.path}</div>
                    <div className="text-[10px] text-neutral-500">{art.type} · {art.size}</div>
                  </div>
                </div>

                <div className="flex items-center gap-1.5 flex-shrink-0">
                  <button
                    onClick={() => handleDownload(art)}
                    className="p-1.5 text-neutral-400 hover:text-white rounded hover:bg-[#2e2e2e] transition-colors cursor-pointer"
                    title={`Download ${art.name}`}
                  >
                    <Download size={14} />
                  </button>
                </div>
              </div>
            ))}
          </div>
        )}
      </div>
    </div>
  );
}
