import React from 'react';
import { 
  Radio, 
  Hash, 
  Zap, 
  Activity, 
  Gauge, 
  Plug, 
  ShieldCheck, 
  Users, 
  CreditCard,
  Plus,
  Check
} from 'lucide-react';

export const CyGenericListPage = ({ tabId, onNewChat, userName = 'SHIKARI' }) => {
  const configs = {
    signals: {
      title: 'Signals',
      subtitle: 'Triggers, webhooks, and event listeners that activate your agents.',
      icon: Radio,
      emptyText: 'No signals configured yet. Create a webhook or event trigger with Cy.'
    },
    artifacts: {
      title: 'Artifacts',
      subtitle: 'Documents, landing pages, code, and exports generated by your agents.',
      icon: Hash,
      emptyText: 'No artifacts generated yet. Ask Cy to create marketing copy, strategy documents, or web pages.'
    },
    skills: {
      title: 'Skills',
      subtitle: 'Capabilities, tool integrations, and reusable actions your agents can execute.',
      icon: Zap,
      emptyText: '24 core skills active (Web search, Marketing strategy, Ad generation, Python runner, CRM sync).'
    },
    runs: {
      title: 'Runs',
      subtitle: 'Execution logs and history of all agent tasks and background jobs.',
      icon: Activity,
      emptyText: '1 run completed in the last 24h.'
    },
    usage: {
      title: 'Usage',
      subtitle: 'Token metrics, agent compute hours, and API consumption.',
      icon: Gauge,
      emptyText: '9,997 of 10,000 credits remaining. Next reset in 28 days.'
    },
    connectors: {
      title: 'Connectors',
      subtitle: 'Third-party integrations with Slack, Google Drive, Apollo, Exa, Twitter, and WhatsApp.',
      icon: Plug,
      emptyText: '2 connectors connected (OpenRouter AI, Web Search). 1,091 available.'
    },
    permissions: {
      title: 'Permissions',
      subtitle: 'Role-based access control, security scopes, and API key permissions.',
      icon: ShieldCheck,
      emptyText: 'Workspace Owner permissions active for ' + userName + '.'
    },
    team: {
      title: 'Team',
      subtitle: 'Collaborators, teammates, and permissions in your organization workspace.',
      icon: Users,
      emptyText: '1 active member: ' + userName + ' (Owner).'
    },
    billing: {
      title: 'Billing & Plan',
      subtitle: 'Manage your subscription, invoices, and credit add-ons.',
      icon: CreditCard,
      emptyText: 'Pro Plan active • 10,000 monthly credits.'
    }
  };

  const current = configs[tabId] || configs.signals;
  const Icon = current.icon;

  return (
    <div className="flex-1 min-h-screen bg-white p-6 sm:p-10 font-sans antialiased text-neutral-900 select-none text-left overflow-y-auto">
      <div className="max-w-5xl mx-auto space-y-8 pt-4 sm:pt-6">
        
        <div className="space-y-1.5">
          <h1 className="text-3xl sm:text-4xl font-serif font-normal text-neutral-900 tracking-tight">
            {current.title}
          </h1>
          <p className="text-xs sm:text-sm text-neutral-500 font-normal">
            {current.subtitle}
          </p>
        </div>

        <div className="bg-white border border-[#e5e5e7] rounded-3xl p-10 sm:p-14 shadow-2xs flex flex-col items-center justify-center text-center space-y-3 min-h-[300px]">
          <div className="w-10 h-10 rounded-2xl bg-neutral-100/70 text-neutral-400 flex items-center justify-center mb-1">
            <Icon size={20} />
          </div>
          
          <h3 className="text-sm font-semibold text-neutral-900">
            {current.title} Status
          </h3>

          <p className="text-xs text-neutral-500 max-w-md leading-relaxed">
            {current.emptyText}
          </p>

          <button
            onClick={onNewChat}
            className="mt-2 text-xs font-semibold bg-neutral-900 hover:bg-neutral-800 text-white px-4 py-2 rounded-xl transition cursor-pointer shadow-xs inline-flex items-center gap-1.5"
          >
            <Plus size={13} />
            <span>Configure with Cy</span>
          </button>
        </div>

      </div>
    </div>
  );
};
