import React from 'react';
import { 
  Radio, 
  Hash, 
  Zap, 
  Activity, 
  Gauge, 
  Plug, 
  ShieldCheck, 
  Users, 
  CreditCard,
  Plus,
  Check,
  Sparkles
} from 'lucide-react';

export const CyGenericListPage = ({ tabId, onNewChat, userName = 'SHIKARI' }) => {
  const configs = {
    artifacts: {
      title: 'Artifacts',
      subtitle: 'Documents, landing pages, copy frameworks, and exports generated by Calvras.',
      icon: Hash,
      emptyText: 'No artifacts generated yet. Ask Calvras in Chat to generate marketing copy, campaign roadmaps, or landing pages.'
    },
    runs: {
      title: 'Runs',
      subtitle: 'Execution logs and history of all campaign runs and autonomous tasks.',
      icon: Activity,
      emptyText: 'All background campaign runs are healthy and synchronized.'
    },
    usage: {
      title: 'Usage',
      subtitle: 'Marketing credit telemetry, compute consumption, and plan allocation.',
      icon: Gauge,
      emptyText: 'Active billing cycle in progress. Instant credit reset on plan renewal.'
    },
    permissions: {
      title: 'Permissions',
      subtitle: 'Role-based access control, security scopes, and commercial IP licenses.',
      icon: ShieldCheck,
      emptyText: 'Workspace Owner permissions and 100% Commercial IP ownership active for ' + userName + '.'
    }
  };

  const current = configs[tabId] || configs.artifacts;
  const Icon = current.icon;

  return (
    <div className="flex-1 min-h-screen bg-[#1c1c1c] text-[#f4f4ee] p-6 sm:p-10 font-sans antialiased text-white select-none text-left overflow-y-auto">
      <div className="max-w-5xl mx-auto space-y-8 pt-4 sm:pt-6">
        
        <div className="space-y-1.5 border-b border-white/10 pb-6">
          <h1 className="text-3xl sm:text-4xl font-serif font-normal text-white tracking-tight">
            {current.title}
          </h1>
          <p className="text-xs sm:text-sm text-neutral-400 font-normal">
            {current.subtitle}
          </p>
        </div>

        <div className="bg-[#282828] border border-white/10 rounded-3xl p-10 sm:p-14 shadow-2xs flex flex-col items-center justify-center text-center space-y-4 min-h-[320px]">
          <div className="w-12 h-12 rounded-2xl bg-neutral-100/80 border border-white/10 text-neutral-600 flex items-center justify-center mb-1 shadow-sm">
            <Icon size={22} />
          </div>
          
          <h3 className="text-base font-bold text-white tracking-tight">
            {current.title} Status
          </h3>

          <p className="text-xs text-neutral-400 max-w-md leading-relaxed">
            {current.emptyText}
          </p>

          <div className="pt-2">
            <button
              onClick={onNewChat}
              className="px-5 py-2.5 rounded-xl bg-neutral-900 hover:bg-neutral-800 text-white text-xs font-bold transition cursor-pointer shadow-sm active:scale-95 flex items-center gap-2"
            >
              <Sparkles size={14} className="text-white" />
              <span>Create with Calvras</span>
            </button>
          </div>
        </div>

      </div>
    </div>
  );
};
